### ISSUE TITLE
Write feature

### ISSUE THREAD

**Issue by gugaoliveira** [Calo-software/flutter_zebra_rfid#1]
Do you plan to create the write feature, to be able to write tags?

**Comment by JarrodLodge** [comment]
This is something not currently on the roadmap, so I can't give you a timeline for this feature.

**Comment by gugaoliveira** [comment]
Can we help you in some way? Zebra doesn't provide dart library to the RFID SDK, but we need to be able to write tags too, so we can help. How do you think?

**Comment by JarrodLodge** [comment]
If you want to fork and build that part your self you are welcome to do that and then submit a pull request. But we currently don't have the capacity to do it.

**Comment by gugaoliveira** [comment]
Yes, thanks I will do that
